version: "3.9"
services:
    api:
        image: devhours.cloudnative.api
        ports:
            - "5000:80"
        environment:
            Cors__AllowedOrigins__0: "http://localhost:4200"
    frontend:
        image:  devhours.cloudnative.frontend
        ports:
            - "4200:80"
        environment:
            webapi: "http://localhost:5000/api"
    db:
        image: "mcr.microsoft.com/mssql/server"
        ports: 
            - "1433:1433"
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"
    storage: 
        image: mcr.microsoft.com/azure-storage/azurite
        ports:
            - "10000:10000"
    