version: "3.9"
services:
    api:
        image: devhours.cloudnative.api
        ports:
            - "5000:80"
        environment:
            Cors__AllowedOrigins__0: "http://localhost:4200"
            ConnectionStrings__HotelDbConnection: "User ID=postgres;Password=example;Host=db;Port=5432;Database=myDataBase;"
        depends_on: 
            - db
    frontend:
        image:  devhours.cloudnative.frontend
        ports:
            - "4200:80"
        environment:
            webapi: "http://localhost:5000/api"
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: example
    storage: 
        image: mcr.microsoft.com/azure-storage/azurite
        ports:
            - "10000:10000"
    