version: "3.9"
services:
    
    api:
        image: devhours.cloudnative.api
        ports:
            - "5000:80"
        environment:
            Cors__AllowedOrigins__0: "http://localhost:4200"
            ConnectionStrings__HotelDbConnection: "User ID=postgres;Password=example;Host=db;Port=5432;Database=HotelDb;"
        depends_on:
            - db

    frontend:
        image: devhours.cloudnative.frontend
        ports:
            - "4200:80"
        environment:
            webapi: "http://localhost:5000/api"

    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: example
    