@uri = https://localhost:5001

@roomsuri = {{uri}}/api/rooms

###

GET {{roomsuri}}?skip=0&take=2

###

POST {{roomsuri}}
Content-Type: application/json

{
    "Description": "This is a new room"
}

###

PUT {{roomsuri}}/1
Content-Type: application/json

{
    "Id": 1,
    "Description": "This is a room description looong"
}

###

GET {{roomsuri}}/1


###

DELETE {{roomsuri}}/1